### ISSUE TITLE
How to build src ?

### ISSUE THREAD

**Issue by batooo** [enyim/EnyimMemcached#111]
Hey all,
I`m kinda noowbie and never used powershell, but ill tell you what i want to make.

I want check dead node is found to add "Send email" or "Do some other staff", just to make sure i shutdown my node and flush everything in it. 

This will help me, when node come back so memcached dont have duplicate key.

As i saw on net, if i have 3 servers and key "test" in on 3th one, when 3th on drop i set "test" on 2nd, but when 3th server come online, it may heppen to get the "test" get from 3th server again, even i stored in 2nd.  Thats why i want check memcached detect dead node, to be sure it dead..and flush it.

So how i can build memcached src? Powershell? What is private snk?

**Comment by kbalint** [comment]
Solution: it is not enough to set all Signing to 'off' in the project's properties, because there is an include in each .csproj file to build\CommonProperties.target where the SignAssembly flag is explicitly set to 'true' again. Set 'false' here if you want to disable signing.
