### ISSUE TITLE
Potential Bug with KetamaNodeLocator and DefaultServerPool

### ISSUE THREAD

**Issue by sirdavidwong** [enyim/EnyimMemcached#113]
I think I've uncovered a bug in the way the KetamaNodeLocator and DefaultServerPool interact. My Enyim setup consists of 2 servers, S1 and S2, and specifying the KetamaNodeLocator as my locator.

The bug occurs when I simulate servers S1 and S2 going on and offline. If I start out with S1 and S2 online, and I take down S1, the keys on S1 will redistribute to S2. However, when S1 comes back online, its keys don't map back to S1. In fact, if I take S1 down again, the server pool won't even detect that. At this point all keys map to S2.

Afterwards, if I take S2 down, S2 is marked as dead and all keys begin to map to S1. If I bring S2 back online, again, keys do not map correctly to S2. All keys map to S1. If S2 is taken down again, the server pool won't detect it.

I believe this is a bug relating to how the DefaultServerPool.NodeFail method and KetamaNodeLocator.Initialize method interact. 

KetamaNodeLocator.Initialize initializes its ring of servers only once. Any attempts to do so afterwards will just return.
https://github.com/enyim/EnyimMemcached/blob/master/Enyim.Caching/Memcached/Locators/KetamaNodeLocator.cs#L59

DefaultServerPool.NodeFail creates a new instance of a locator after a node failure is detected. It initializes the the locator with only the servers that are currently alive:
https://github.com/enyim/EnyimMemcached/blob/master/Enyim.Caching/Memcached/DefaultServerPool.cs#L159

In the case of the bug, when S1 is taken offline, a ketama node locator is created and initialized with only S2.

When DefaultServerPool.rezCallback tries to reinitialize the locator if it detects a server has come back online, the KetamaNodeLocator will just return.
https://github.com/enyim/EnyimMemcached/blob/master/Enyim.Caching/Memcached/DefaultServerPool.cs#L118

So when S1 comes back online, there's no way for the already initialized locator to know it's available. When I take S2 down, NodeFail is called again, but this time a new ketama node locator is created with only S1. The same logic applies when S2 comes back online -- it is ignored.

Please let me know what you think about this. One other question: is there an configurable option to choose whether or not to redistribute keys to other servers when a server is dead for the KetamaNodeLocator?
https://github.com/enyim/EnyimMemcached/blob/master/Enyim.Caching/Memcached/Locators/KetamaNodeLocator.cs#L150

In some cases, it'd be helpful to turn this off.

**Comment by daryl-mcmillan** [comment]
I have some details on this issue that may be helpful.

When a node fails, the `DefaultServerPool` creates a new NodeLocator with only the healthy nodes:
https://github.com/enyim/EnyimMemcached/blob/develop/Enyim.Caching/Memcached/DefaultServerPool.cs#L159

When a node recovers it doesn't re-create the NodeLocator, it just makes a call to Initialize:  https://github.com/enyim/EnyimMemcached/blob/develop/Enyim.Caching/Memcached/DefaultServerPool.cs#L118

The KetamaNodeLocator expects the opposite: it wants to be initialized with the full node list and ignores additional calls to Initialize: https://github.com/enyim/EnyimMemcached/blob/develop/Enyim.Caching/Memcached/Locators/KetamaNodeLocator.cs#L59
