### ISSUE TITLE
Strong name signature could not be verified

### ISSUE THREAD

**Issue by peteski22** [enyim/EnyimMemcached#119]
I obtained Enyim.Caching from Nuget (Install-Package EnyimMemcached), builds fine but I get a runtime error when I try to debug (Windows Server 2003 R2 x64 - SP2, .NET 4.0.3):

Could not load file or assembly 'Enyim.Caching' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045).

Is there something I'm not doing? I don't want to start changing settings on the machine level for one assembly.

Out of interest, installing the previous version does not give this error:

Install-Package EnyimMemcached -Version 2.11

**Comment by suershkvish** [comment]
Ca any one tell the process and solution for the below issue. 

Could not load file or assembly 'Enyim.Caching' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

Could not load file or assembly 'Enyim.Caching, Version=2.16.0.0, Culture=neutral, PublicKeyToken=cec98615db04012e' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]
