### ISSUE TITLE
DateTime expiresAt Error ?

### ISSUE THREAD

**Issue by myunQ** [enyim/EnyimMemcached#144]
namespace Enyim.Caching
{
      public class MemcachedClient 
       {

            protected static readonly DateTime UnixEpoch = new DateTime(1970, 1, 1);

            //error method
            protected static uint GetExpiration(DateTime expiresAt){
			if (expiresAt < UnixEpoch) throw new ArgumentOutOfRangeException("expiresAt", "expiresAt must be >= 1970/1/1");

			// accept MaxValue as infinite
			if (expiresAt == DateTime.MaxValue) return 0;

                        //unix timestamp not Memcached cache timeout parameter value.
			uint retval = (uint)(expiresAt.ToUniversalTime() - UnixEpoch).TotalSeconds;

			return retval;
            }
      }
}

**Comment by myunQ** [comment]
protected static uint GetExpiration(DateTime expiresAt)
{
    if (expiresAt < DateTime.UtcNow) throw new ArgumentOutOfRangeException("expiresAt", "expiresAt must be later than now");

    // accept MaxValue as infinite
    if (expiresAt == DateTime.MaxValue) return 0;

    uint retval = (uint)(expiresAt.ToUniversalTime() - DateTime.UtcNow).TotalSeconds;

    return retval;
}

**Comment by enyim** [comment]
works as intended; timestamps less than now can be used to expire items in the cache
