### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object in ReleaseSocket()

### ISSUE THREAD

**Issue by joelnet** [enyim/EnyimMemcached#145]
We are getting the following error on occasion. Installed via nuget. Version: 2.12.

```
[NullReferenceException: Object reference not set to an instance of an object.]
   Enyim.Caching.Memcached.InternalPoolImpl.ReleaseSocket(PooledSocket socket) in d:\Dropbox\repo\EnyimMemcached\Enyim.Caching\Memcached\MemcachedNode.cs:430
   Enyim.Caching.Memcached.PooledSocket.Dispose(Boolean disposing) in d:\Dropbox\repo\EnyimMemcached\Enyim.Caching\Memcached\PooledSocket.cs:158
   Enyim.Caching.Memcached.MemcachedNode.ExecuteOperation(IOperation op) in d:\Dropbox\repo\EnyimMemcached\Enyim.Caching\Memcached\MemcachedNode.cs:545
   Enyim.Caching.MemcachedClient.PerformTryGet(String key, UInt64& cas, Object& value) in d:\Dropbox\repo\EnyimMemcached\Enyim.Caching\MemcachedClient.cs:191
   Enyim.Caching.MemcachedClient.TryGet(String key, Object& value) in d:\Dropbox\repo\EnyimMemcached\Enyim.Caching\MemcachedClient.cs:150
   Enyim.Caching.MemcachedClient.Get(String key) in d:\Dropbox\repo\EnyimMemcached\Enyim.Caching\MemcachedClient.cs:137
   Global.Data.Caching.Memcached.MemcachedCacheProvider.Get(String key) in C:\Projects\net2\Data\Caching\Memcached\MemcachedCacheProvider.cs:152
```

**Comment by odymonish** [comment]
hi - did you ever find out anything on this? We are having the same error.
Thanks to advise.

**Comment by joelnet** [comment]
Never resolved. I am no longer working on this project so I do not know the state of it, sorry I can't help more.

**Comment by dsargent3220** [comment]
Good morning.  We think this may be causing site instability on our test server.  Our prod servers have only one site installed and thus one copy of memcached and one instance of Enyim running, though we are running 4 threads (app pools) for each site and are thus OK.  However on the test server we are running multiple sites and when we added the last site and another copy of memcached everything become very unstable.  We finally tracked it down to running out of ports.  When we shut down the extra site and memcached the port counts went down.  It looks like that maybe this null ref exception is keeping enyim from closing the port in a timely manner and thus using up too many ports.  
Doe this sound likely?
Our build / deploy system uses nuget to deploy the dependant packages so it would be difficult to test the beta out on the test server.  Do you think this would solve our problem?  Should I put more effort into replicating our test environment locally and seeing if the beta fixes it?
If you think this will fix it, how long until you have a version out on NuGet for us to consume?

**Comment by odymonish** [comment]
We use nuget as well however you will find a packages folder where you can update the dll. This does require a reference update and will need a full project update but it works well from what we can tell.

Sent from my iPhone, please excuse typos

On May 18, 2016, at 11:15 AM, dsargent3220 <notifications@github.com<mailto:notifications@github.com>> wrote:


Good morning. We think this may be causing site instability on our test server. Our prod servers have only one site installed and thus one copy of memcached and one instance of Enyim running, though we are running 4 threads (app pools) for each site and are thus OK. However on the test server we are running multiple sites and when we added the last site and another copy of memcached everything become very unstable. We finally tracked it down to running out of ports. When we shut down the extra site and memcached the port counts went down. It looks like that maybe this null ref exception is keeping enyim from closing the port in a timely manner and thus using up too many ports.

Doe this sound likely?
Our build / deploy system uses nuget to deploy the dependant packages so it would be difficult to test the beta out on the test server. Do you think this would solve our problem? Should I put more effort into replicating our test environment locally and seeing if the beta fixes it?
If you think this will fix it, how long until you have a version out on NuGet for us to consume?

-

**Comment by enyim** [comment]
hm, this makes sense

the NRE was coming from the cleanup code, and i could not figure out why it fails, as i assumed it was initialized correctly :)

so right now the cleanup code has a bunch of extra error handling, but this only hides the issue

i'll do another pass on it, but meanwhile i can push the current beta as a pre-release nuget package in a couple of days, if it makes your testing process easier

**Comment by dsargent3220** [comment]
Hi odymonish, Yeah, I know about the packages folder, but we don't check the packages into our source control and our build system uses our repo for the source for code and nuget for the libraries.  We can hack it for testing.  For now I'm replicating the test server locally to turn the problem on and off to see if the new DLL fixes it or not.  Still in process, will update when I find out more.
