### ISSUE TITLE
Object Reference Error

### ISSUE THREAD

**Issue by odymonish** [enyim/EnyimMemcached#148]
Hello, we are using 3 servers in our Memcache environment. Earlier we had 2 servers and never saw this error - over the last week since we have added a 3rd server we are always seeing this error:

Message:Object reference not set to an instance of an object.

StackTrace: at Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl.ReleaseSocket(PooledSocket socket) in d:\Dropbox\Repo\EnyimMemcached\Enyim.Caching\Memcached\MemcachedNode.cs:line 430 at Enyim.Caching.Memcached.PooledSocket.Dispose(Boolean disposing) in d:\Dropbox\Repo\EnyimMemcached\Enyim.Caching\Memcached\PooledSocket.cs:line 158 at Enyim.Caching.Memcached.MemcachedNode.ExecuteOperation(IOperation op) in d:\Dropbox\Repo\EnyimMemcached\Enyim.Caching\Memcached\MemcachedNode.cs:line 545 at Enyim.Caching.MemcachedClient.PerformTryGet(String key, UInt64& cas, Object& value) in d:\Dropbox\Repo\EnyimMemcached\Enyim.Caching\MemcachedClient.cs:line 194 at Enyim.Caching.MemcachedClient.ExecuteGet(String key) in d:\Dropbox\Repo\EnyimMemcached\Enyim.Caching\MemcachedClient.Results.cs:line 133 

Can you please explain what if anything can be done with this?

**Comment by enyim** [comment]
I think I have an idea why this is happening. Working on it.

**Comment by odymonish** [comment]
Thank you! Please let me know.

Sent from my iPhone, please excuse typos

On Apr 20, 2016, at 6:23 PM, Attila Kisk? <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I have an idea why this is happening. Working on it.

-

**Comment by enyim** [comment]
Can you please test [this release](https://github.com/enyim/EnyimMemcached/releases/tag/v2.13.1-beta) for a while?

Unfortunately I cannot reproduce the bug locally.

**Comment by enyim** [comment]
#145

**Comment by odymonish** [comment]
Thanks! I’ve downloaded the files and will be testing this week – will keep you posted.



 - Monish
monish@OdysseusSolutions.com<mailto:monish@OdysseusSolutions.com>

Support Site & Knowledgebase
http://Support.OdySol.com/<http://odysseus.helpserve.com/index.php>

t: +1 (305) 804-4177
c: +1 (917) 674-4181

14740 SW 80th Ave, Miami, FL 33158

**Comment by odymonish** [comment]
I wanted to share that this is working well for us.

We have had this in production for a couple weeks now and have not seen those errors that we were getting earlier.

Sent from my iPhone, please excuse typos

On Apr 24, 2016, at 1:22 PM, Attila Kisk? <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please test this release<https://github.com/enyim/EnyimMemcached/releases/tag/v2.13.1-beta> for a while?

Unfortunately I cannot reproduce the bug locally.

-

**Comment by enyim** [comment]
https://www.nuget.org/packages/EnyimMemcached/2.14.0-rc1

**Comment by odymonish** [comment]
Hi

Thanks so much for your help. I have a question, we use 3 servers in our mix and an issue that we run into is that when one of them stops responding - it's not being removed from the mix - instead we are seeing major delays in response and a melt down at time of insert and read.

What would be nice is if the server would be removed from mix after a set of failures and a notification. Of course this should be configurable.

Sent from my iPhone, please excuse typos

On May 20, 2016, at 6:43 PM, Attila Kisk? <notifications@github.com<mailto:notifications@github.com>> wrote:


https://www.nuget.org/packages/EnyimMemcached/2.14.0-rc1

-
