### ISSUE TITLE
ProviderElement stores broken/uninitialized factory instances

### ISSUE THREAD

**Issue by NathanBaulch** [enyim/EnyimMemcached#151]
`ProviderElement<T>.CreateInstance` shouldn't set the `factoryInstance` field until after `IProviderFactory<T>.Initialize` has successfully executed. I'm experiencing confusing errors because `DefaultPerformanceMonitorFactory` is failing to initialize but the instance is still being retained for future use.

Pretty easy to reproduce:
```csharp
var config = new ProviderElement<IPerformanceMonitor>
    {
        Factory = typeof(DefaultPerformanceMonitorFactory)
    };
try
{
    config.CreateInstance();
}
catch (Exception)
{
    //swallow factory initialize failure
}
try
{
    config.CreateInstance();
}
catch (Exception)
{
    //different more confusing error
}
```

**Comment by enyim** [comment]
Swallowing an exception is never a good idea :)

Anyway, fixed by throwing an InvalidOperationException with a descriptive message.
