### ISSUE TITLE
TCP KeepAlive does not work

### ISSUE THREAD

**Issue by vchekan** [enyim/EnyimMemcached#93]
As I can not reopen ticket https://github.com/enyim/EnyimMemcached/issues/85, I have to open a new one.
The issue with current keepalive implementation is that it does not set interval. In Windows default keepalive interval is 2hr which is not enough for many firewalls. 
Here is implementation which sets keeplive to 5min:
https://github.com/vchekan/EnyimMemcached/commit/8e270773574991c7c9834f43d1eff2b905e981e2

**Comment by thebitllc** [comment]
Hi,

We have a similar problem with the default timeout. It isn't frequent enough for our firewall and the connections are abruptly getting closed and memcached nodes are getting marked dead.
